services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: imdb_scrapper
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

    environment:
      - CHROME_WS_URL=ws://chrome:3000
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: postgres:15
    container_name: imdb_database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: